server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: local


  datasource:
    password: talent
    username: root
    url: jdbc:mysql://127.0.0.1:3307/orange?useSSL=false&AllowPublicKeyRetrieval=true
    testWhileIdle: true
    validationQuery: Select 1

    jpa:
      hibernate:
        ddl-auto: none
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true



#Swagger Properties

swagger:
  api:
    title: App-Orange-Talent
    description: Luiz Felipe Braga
    termsOfServiceUrl: https://github.com/luizfelipebraga
    version: 1.0
    controller:
      basepackage: com.orange.talent.account.controller
