server:
  port: 8081
  servlet:
    context-path: /api


spring:
  profiles:
    active: local
  kafka:
    producer:
      bootstrap-servers: localhost:29092
    # consumer:
    #   group-id: group-id
    #   auto-offset-reset: earliest

  datasource:
    password: talent
    username: root
    url: jdbc:mysql://127.0.0.1:3307/orange?useSSL=false&AllowPublicKeyRetrieval=true
    testWhileIdle: true
    validationQuery: Select 1

    jpa:
      hibernate:
        ddl-auto: none
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true



#Swagger Properties

swagger:
  api:
    title: App-Orange-Talent
    description: Luiz Felipe Braga
    termsOfServiceUrl: https://github.com/luizfelipebraga
    version: 1.0
    controller:
      basepackage: com.orange.talent.account.controller

client-kafka:
  topic: kafka-python-topic